#!/bin/bash -x

go version | grep -q go1.5

if [ "x$?" != "x0" ]; then
    export GOROOT=$(pwd)/goroot/go
    wget https://storage.googleapis.com/golang/go1.5.1.linux-amd64.tar.gz -O go.tar.gz
    mkdir -p ${GOROOT}; tar -C ${GOROOT} -xf go.tar.gz
    rm -f go.tar.gz
    export PATH=${GOROOT}/bin:$PATH
fi

export GO15VENDOREXPERIMENT=1
export GOPATH=$(pwd)/gopath
export ORG_PATH=github.com/vtolstov
export REPO_PATH=${ORG_PATH}/cloud-install

rm -rf ${GOPATH}
mkdir -p ${GOPATH}/src/${ORG_PATH}

ln -sv ../../../.. ${GOPATH}/src/${REPO_PATH}

export GOOS=linux
if [ "x$1" = "xx86_64" ]; then
   export GOARCH=amd64
elif [ "x$1" = "xx86_32" ]; then
   export GOARCH=386
fi

go build -x -tags netgo -o $2 ${REPO_PATH}

test -e $2 || exit 255;
